# Generated by Django 5.2.8 on 2025-11-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_user_type_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('medico', 'Médico'), ('enfermeiro', 'Enfermeiro')], default='enfermeiro', max_length=20),
        ),
    ]
